version: "3"

services:
  consul:
    image: consul
    container_name: consul
    networks:
      - consul-demo
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    # command: "agent -dev -bootstrap-expect 1 -ui -client 0.0.0.0"
    # command: "agent -dev"

networks:
  consul-demo: